name: "Test"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run type check
        run: npm run type-check

  alert:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ failure() }}
    steps:
      - name: Notify failure
        run: echo "❌ Tests failed! Check the workflow logs for details."
